version: "2"
services:    
  server-app-caique:
    container_name: "server-app-caique"
    restart: always
    build: './server'
    environment:
      - PORT=3333
    ports:
      - "3333:3333"
    links:
      - mongo-app-caique
    depends_on:
      - mongo-app-caique
    command: yarn start
    
  web-app-caique:
    container_name: "web-app-caique"
    build: './web'
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    command: yarn start

  mongo-app-caique:
    container_name: "mongo-app-caique"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet
    
  server-app-caique-test:
    container_name: "server-app-caique-test"
    restart: always
    build: './server'
    links:
      - mongo-app-caique
    depends_on:
      - mongo-app-caique
    command: yarn test
    
  web-app-caique-test:
    container_name: "web-app-caique-test"
    build: './web'
    command: yarn test